<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  '<p>No matches found.</p><p><b>Create the category first!<b></p>' => '',
  'Add' => '',
  'Add Comment' => '',
  'Are you sure ?' => '',
  'Close' => '',
  'Comment' => '',
  'Could not refresh write lock' => '',
  'Could not save script: A server side error occured. Please contact an admin.
Status:' => '',
  'Could not save tree: A server side error occured. Please contact an admin.
Status:' => '',
  'Create category' => '',
  'Error' => '',
  'Error while deleting Thread!' => '',
  'Error while loading Thread!' => '',
  'Error while saving' => '',
  'Expected a block node' => '',
  'New category' => '',
  'Single node expected' => '',
  'You have to insert a name for the category' => '',
  'You have to remove the \'#\' in the Name' => '',
  'delete Thread' => '',
  'edit category' => '',
  'keys' => '',
  'reply' => '',
  'you are not able to delete the root' => '',
);
