<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  '<p>No matches found.</p><p><b>Create the category first!<b></p>' => '',
  'Are you sure ?' => '',
  'Could not refresh write lock' => '',
  'Could not save script: A server side error occured. Please contact an admin.
Status:' => '',
  'Could not save tree: A server side error occured. Please contact an admin.
Status:' => '',
  'Error while deleting Thread!' => '',
  'Error while loading Thread!' => '',
  'You have to insert a name for the category' => '',
  'You have to remove the \'#\' in the Name' => '',
  'delete Thread' => '',
  'reply' => '',
  'Add' => 'Hinzufügen',
  'Add Comment' => 'Kommentar hinzufügen',
  'Close' => 'Schließen',
  'Comment' => 'Kommentar',
  'Create category' => 'Kategorie erstellen',
  'Error' => 'Fehler',
  'Error while saving' => 'Fehler während speichern',
  'Expected a block node' => 'erwartete einen node block',
  'New category' => 'neue Kategorie',
  'Single node expected' => 'erwartete einen einzelnen node',
  'edit category' => 'Kategorie bearbeiten',
  'keys' => 'Schlüssel',
  'you are not able to delete the root' => 'Du kannst die Wurzel nicht löschen',
);
