<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  '<p>No matches found.</p><p><b>Create the category first!<b></p>' => '<p>Sem resultados.</p><p><b>Crie a categoria primeiro!<b></p>',
  'Are you sure ?' => 'Tem a certeza?',
  'Could not refresh write lock' => 'Não foi possível atualizar',
  'Could not save script: A server side error occured. Please contact an admin.
Status:' => 'Não foi possível gravar guião: ocorreu um erro no servidor. Por favor contacte um admin. Status:',
  'Could not save tree: A server side error occured. Please contact an admin.
Status:' => 'Não foi possível gravar árvore: ocorreu um erro no servidor. Por favor contacte um admin. Status:',
  'Error while deleting Thread!' => 'Erro ao apagar discussão!',
  'Error while loading Thread!' => 'Erro ao carregar discussão!',
  'Expected a block node' => '',
  'Single node expected' => '',
  'You have to insert a name for the category' => 'Tem de inserir um nome para a categoria',
  'You have to remove the \'#\' in the Name' => 'Tem de remover \'#\' do nome',
  'delete Thread' => 'Apagar discussão',
  'reply' => 'Responder',
  'Add' => 'Adicionar',
  'Add Comment' => 'Comentar',
  'Close' => 'Fechar',
  'Comment' => 'Comentários',
  'Create category' => 'Criar categoria',
  'Error' => 'Erro',
  'Error while saving' => 'Erro ao gravar',
  'New category' => 'Nova categoria',
  'edit category' => 'Editar categoria',
  'keys' => 'teclas',
  'you are not able to delete the root' => 'Não pode apagar a raiz',
);
