<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Could not refresh write lock' => 'TEST',
  'You have to insert a name for the category' => 'TEST',
  'You have to remove the \'#\' in the Name' => 'TEST',
  '<p>No matches found.</p><p><b>Create the category first!<b></p>' => 'TEST',
  'Add' => 'TEST',
  'Add Comment' => 'TEST',
  'Are you sure ?' => 'TEST',
  'Close' => 'TEST',
  'Comment' => 'TEST',
  'Could not save script: A server side error occured. Please contact an admin.
Status:' => 'TEST',
  'Could not save tree: A server side error occured. Please contact an admin.
Status:' => 'TEST',
  'Create category' => 'TEST',
  'Error' => 'TEST',
  'Error while deleting Thread!' => 'TEST',
  'Error while loading Thread!' => 'TEST',
  'Error while saving' => 'TEST',
  'Expected a block node' => 'TEST',
  'New category' => 'TEST',
  'Single node expected' => 'TEST',
  'delete Thread' => 'TEST',
  'edit category' => 'TEST',
  'keys' => 'TEST',
  'reply' => 'TEST',
  'you are not able to delete the root' => 'TEST',
);
